"""
#REPEAT A BLOCK OF CODE SEVERALLY
#ITERATE OVER A SEQUENCE
 SYNTAX
   FOR VARIABLE IN SEQUENCE
      //VALID PYTHON STATEMENTS
      FOR WILL LOOPS WHILE ITERATING OVER A SEQUENCE WILL ONLY TERMINATE WHEN THE LAST ELEEMNT IS REACHED
      

student = ["Name":kevin]
for k,v in student.items
 print(k,v)
"""
#sum of all odd numbers from to 20



for i in range(10,num+1):
    if i/2==1:
        print(i)
        evensum+=i

print(evensum)
